name: enkoy_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  awesome_notifications: ^0.10.1
  cloud_firestore: ^6.0.3
  collection: ^1.19.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  firebase_messaging: ^16.0.3
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  fluttertoast: ^8.2.14
  freezed_annotation: ^2.4.4
  google_fonts: ^6.3.2
  json_annotation: ^4.9.0
  nb_utils: ^7.1.8
  shared_preferences: ^2.5.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  google_sign_in: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  

flutter:
  assets:
    - assets/images/
  uses-material-design: true

