name: chat
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^4.12.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.16.0
  intl: ^0.19.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: 17.2.1
  cloud_functions: ^4.6.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  image_picker: ^1.1.2
  firebase_storage: ^11.6.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  
  uses-material-design: true

  assets:
    - .env
 